INSERT into Algorithm(A_ID) Values('1');
Insert into Questionnaire(Q_ID, numQ, name, Algorithm_A_ID) Values('1', '10', 'PHQ9', '1');
Insert into Question(Qu_ID, num, Questionnaire_Q_ID) Values('1','1','1');
Insert into Question(Qu_ID, num, Questionnaire_Q_ID) Values('2','2','1');
Insert into Question(Qu_ID, num, Questionnaire_Q_ID) Values('3','3','1');
Insert into Question(Qu_ID, num, Questionnaire_Q_ID) Values('4','4','1');
Insert into Question(Qu_ID, num, Questionnaire_Q_ID) Values('5','5','1');
Insert into Question(Qu_ID, num, Questionnaire_Q_ID) Values('6','6','1');
Insert into Question(Qu_ID, num, Questionnaire_Q_ID) Values('7','7','1');
Insert into Question(Qu_ID, num, Questionnaire_Q_ID) Values('8','8','1');
Insert into Question(Qu_ID, num, Questionnaire_Q_ID) Values('9','9','1');
Insert into Question(Qu_ID, num, Questionnaire_Q_ID) Values('10','10','1');